### ISSUE TITLE
NextJs | Metronic 9 document

### ISSUE THREAD

**Issue by zakeri-dev** [keenthemes/metronic-tailwind-html-integration#1]
Hello and have a good time
Also, thank you very much for the wonderful metronic
Please make a document to integrate Html_Tailwind with the NextJs Page router version
We are in dire need

**Comment by KeenthemesHub** [comment]
Hi,

Thank you for your feedback. Agree, this is an important feature and we will consider implementing this guide.
if you have any further feedback or request please do let us know.

Regards,
Sean

**Comment by zakeri-dev** [comment]
Thank you very much for your reply
we are waiting for "soon" pages in the very beautiful  Metronic v9
and documents related to NextJs
❤

**Comment by zakeri-dev** [comment]
> Hi,
> 
> Thank you for your feedback. Agree, this is an important feature and we will consider implementing this guide. if you have any further feedback or request please do let us know.
> 
> Regards, Sean

Thank you very much for your reply
we are waiting for "soon" pages in the very beautiful Metronic v9
and documents related to NextJs
❤

**Comment by keenthemes** [comment]
@zakeri-dev Sure, we will expedite it.

**Comment by laaraujo** [comment]
Hey @keenthemes.
By any chance is there an ETA for the Next integration ?

**Comment by laurisstepanovs** [comment]
@laaraujo @zakeri-dev
The Metronic 9 and NextJs integration example is already available in this repo, you can follow instructions from [README.md](https://github.com/keenthemes/metronic-tailwind-html-integration/blob/main/metronic-tailwind-next/README.md) to set the example up.

The full integration documentation will be available in a few days.

**Comment by dwicahyo-dev** [comment]
Hi there!

Any updates regarding integration documentation nextjs app router ?
