### ISSUE TITLE
Integration Failure on new Laravel project

### ISSUE THREAD

**Issue by lmly9193** [keenthemes/metronic-tailwind-html-integration#10]
Hi, I am using this template as the basis for a new Laravel project.

## Problems

I have followed the [steps](https://keenthemes.com/metronic/tailwind/docs/getting-started/integration/laravel#download) below to build the project, but my site looks like it is unfinished. I should be missing something, but I can't find the problem. Could you help?

## Screenshots
![image](https://github.com/user-attachments/assets/4e090864-978c-4c3f-9311-2e18a94bf3f3)

![image](https://github.com/user-attachments/assets/e0ed0391-940a-464b-a6dd-80d62c9994f3)

## Work with Laravel Starter Kits?

Btw, Could you please provide a guide on how metronic works with laravel breeze?

**Comment by faizalmy** [comment]
Hi,

Please check the workaround here.

https://github.com/keenthemes/metronic-tailwind-html-integration/issues/4

We will include the fix in the next update soon.

Thanks

**Comment by faizalmy** [comment]
Hi

Please refer to this fix for this file.

/metronic-tailwind-laravel/resources/css/app.scss

Add this line


`@import "../metronic/css/demos/demo1.css";
`

https://github.com/keenthemes/metronic-tailwind-html-integration/commit/8f8a691bc9e1b8b1da6b3cd2c9f205a023ba4f4c

Thank you
