### ISSUE TITLE
Footer is displayed incorrectly - Angular

### ISSUE THREAD

**Issue by ArsenioInojosa** [keenthemes/metronic-tailwind-html-integration#11]
Hello,

I have a problem with the Angular template. When I add a login screen to it, it doesn't use the layout. The routes:

![00](https://github.com/user-attachments/assets/06f8bf02-aa82-4aba-b11a-5fb89aa60a0d)

The login component and its route. It's fine.
![01](https://github.com/user-attachments/assets/e71ab0d5-1ce6-4ce8-9d43-252b96b34dd9)

The layout.
![02](https://github.com/user-attachments/assets/8ecb50e8-a9d0-48e1-9240-4754ccf5b2f1)

The problem seems to occur when there is a `<router-outlet></router-outlet>` at a top level.

![03](https://github.com/user-attachments/assets/f50e1b12-b6d2-4b15-b298-93113a0070d1)

Thank you!

**Comment by faizalmy** [comment]
Hi,

We will fix it.

Thank you

**Comment by faizalmy** [comment]
Hi,

Can you please refer to the sample Angular project?

https://github.com/keenthemes/metronic-tailwind-html-integration/tree/main/metronic-tailwind-angular/src/app/layouts/footer


<img width="1714" alt="Screenshot 2024-08-11 at 1 30 00 PM" src="https://github.com/user-attachments/assets/de0f5db0-430a-434c-b0cd-5140edb0d306">

**Comment by ArsenioInojosa** [comment]
Hello,

The application was created with the example files, the footer has not been modified.

The problem arises when adding a login without using the layout. I attach a video:

https://github.com/user-attachments/assets/34a7995d-39c8-4e6a-8f39-3293efec0ff9
