### ISSUE TITLE
Error on React project

### ISSUE THREAD

**Issue by angelcalvasp** [keenthemes/metronic-tailwind-html-integration#12]
Hello there

I followed the instructions on the following link
[Getting Started React Integration ](https://keenthemes.com/metronic/tailwind/docs/getting-started/integration/react)
I specifically tried the download method, I copied the file, ran npm install, ran dev navigated to the site and am getting the following error

"SyntaxError: The requested module '/src/metronic/core/components/dropdown/types.ts' does not provide an export named 'KTDropdownConfigInterface' (at index.ts:2:10)"

which is weird since these modules do exist in the file

just wanted to check if this is a bug or something

**Comment by laurisstepanovs** [comment]
Hi,

Could you please specify which version of Metronic you are using?

Have you made any changes to our `tsconfig.json`?

If you still encounter this error after following the integration guide and using assets from the latest version of Metronic, try setting up and running our [react example app](https://github.com/keenthemes/metronic-tailwind-html-integration/tree/main/metronic-tailwind-react), which already includes all needed configuration files.

Regards,
Lauris Stepanovs,
Keenthemes Support Team
