### ISSUE TITLE
Header is Displayed Incorrectly

### ISSUE THREAD

**Issue by devpela9** [keenthemes/metronic-tailwind-html-integration#13]
Hi, I'm using Laravel 11 and using Metronic 9. The installation is successfull but when I access the index.blade.php which is from index.html from demo1, the header is not displayed correctly. You can check below. 

https://i.imgur.com/cBmI0KH.png

**Comment by faizalmy** [comment]
Hi

Please refer to this fix for this file.

/metronic-tailwind-laravel/resources/css/app.scss

Add this line

`@import "../metronic/css/demos/demo1.css";
`

https://github.com/keenthemes/metronic-tailwind-html-integration/commit/8f8a691bc9e1b8b1da6b3cd2c9f205a023ba4f4c
