### ISSUE TITLE
Dashboard issue with multiple imports on Angular

### ISSUE THREAD

**Issue by Seanahamilton** [keenthemes/metronic-tailwind-html-integration#14]
Adding the following code to `dashboard.component.html` results in none of the widgets being displayed - and only the builder component:

```
<div class="row g-5 gx-xxl-8">
  <div class="col-xxl-4">
    <app-builder></app-builder>
  </div>
</div>
```

I've made sure that `dashboard.module.ts` imports `BuilderModule` and `BuilderModule` exports `BuilderComponent`.

I'm not sure where the issue is coming from. Any help appreciated.

**Comment by faizalmy** [comment]
Hi

When you use `<app-builder></app-builder>`, the `BuilderComponent` will be fixed to that position in your template. If you intend to make it part of the routing system, replace it with a `<router-outlet>` tag. This way, the component can be loaded dynamically based on the route configuration.
