### ISSUE TITLE
New nextjs integration not working

### ISSUE THREAD

**Issue by tomichGIT** [keenthemes/metronic-tailwind-html-integration#5]
I tried both following the steps for a NextJs from scratch, and also using the repo **"metronic-tailwind-next"**

First error i get is  from **tailwind.config.ts** it says "'./src/metronic/core/plugins/layouts/demo1'" can not be found, so i searched the metronic src folder and the only one i found was this one: './src/metronic/app/layouts/demo1' 

try to Fix 1 (tailwind.config.ts):
plugins: [
		require('./src/metronic/core/plugins/plugin'),
		//require('./src/metronic/core/plugins/layouts/demo1'),
		require('./src/metronic/app/layouts/demo1'),
		....
]

then i have this second Compilation Error:
"TypeError: Class constructor KTLayout cannot be invoked without 'new'"

```js
// at the bottom of "src/metronic/app/layout/demo1.js"
...
// KTDom.ready(() => {
// 	KTLayout.init();
// });
export default KTLayout;
```

as the documentation said, you have to add "export default KTLayout;" but its allready there, so i just commented out the KTDom.ready() part , and get the previus error mentioned. From there on i couldnt continue.

i could try to change the globalInit component to use the "new" constructor, but then init() wont run because is a static method.

**Comment by TomasCEI** [comment]
if someone is interested, i fixed the class KTLayout converting the Class insto an object:

```js
// src/metronic/app/layouts/demo1.js

const KTLayout = {
	_isSidebarCollapse() {
		return document.body.classList.contains('sidebar-collapse');
	},
	_handleMegaMenu() {
		const megamenuEl = document.querySelector('#megamenu');
		if (!megamenuEl) return;

		const menu = KTMenu.getInstance(megamenuEl);
		menu.disable();

		setTimeout(() => {
			menu.enable();
		}, 500);
	},
	_handleSidebar() {
		const sidebarToggle = KTToggle.getInstance(this.sidebarToggleEl);
		sidebarToggle?.on('toggle', () => {
			this.sidebarEl.classList.add('animating');

			this._handleMegaMenu();

			KTDom.transitionEnd(this.sidebarEl, () => {
				this.sidebarEl.classList.remove('animating');
			});
		});
	},
	_handleSidebarMenu() {
		const menuEl = document.querySelector('#sidebar_menu');
		const scrollableEl = document.querySelector('#sidebar_scrollable');
		const menuActiveItemEl = menuEl.querySelector(".menu-item.active");

		if (!menuActiveItemEl || KTDom.isVisibleInParent(menuActiveItemEl, scrollableEl)) {
			return;
		}

		scrollableEl.scroll({
			top: KTDom.getRelativeTopPosition(menuActiveItemEl, scrollableEl) - 100,
			behavior: 'instant'
		});
	},
	init() {
		this.sidebarEl = document.querySelector('#sidebar');
		this.sidebarWrapperEl = document.querySelector('#sidebar_wrapper');
		this.headerEl = document.querySelector('#header');
		this.sidebarToggleEl = document.querySelector('#sidebar_toggle');

		if (this.sidebarEl && this.sidebarToggleEl) {
			this._handleSidebar();
			this._handleSidebarMenu();
		}
	},
	isSidebarCollapse() {
		return this._isSidebarCollapse();
	}
}
export default KTLayout;
```

**Comment by kyro95** [comment]
> if someone is interested, i fixed the class KTLayout converting the Class insto an object:
> 
> ```js
> // src/metronic/app/layouts/demo1.js
> 
> const KTLayout = {
> 	_isSidebarCollapse() {
> 		return document.body.classList.contains('sidebar-collapse');
> 	},
> 	_handleMegaMenu() {
> 		const megamenuEl = document.querySelector('#megamenu');
> 		if (!megamenuEl) return;
> 
> 		const menu = KTMenu.getInstance(megamenuEl);
> 		menu.disable();
> 
> 		setTimeout(() => {
> 			menu.enable();
> 		}, 500);
> 	},
> 	_handleSidebar() {
> 		const sidebarToggle = KTToggle.getInstance(this.sidebarToggleEl);
> 		sidebarToggle?.on('toggle', () => {
> 			this.sidebarEl.classList.add('animating');
> 
> 			this._handleMegaMenu();
> 
> 			KTDom.transitionEnd(this.sidebarEl, () => {
> 				this.sidebarEl.classList.remove('animating');
> 			});
> 		});
> 	},
> 	_handleSidebarMenu() {
> 		const menuEl = document.querySelector('#sidebar_menu');
> 		const scrollableEl = document.querySelector('#sidebar_scrollable');
> 		const menuActiveItemEl = menuEl.querySelector(".menu-item.active");
> 
> 		if (!menuActiveItemEl || KTDom.isVisibleInParent(menuActiveItemEl, scrollableEl)) {
> 			return;
> 		}
> 
> 		scrollableEl.scroll({
> 			top: KTDom.getRelativeTopPosition(menuActiveItemEl, scrollableEl) - 100,
> 			behavior: 'instant'
> 		});
> 	},
> 	init() {
> 		this.sidebarEl = document.querySelector('#sidebar');
> 		this.sidebarWrapperEl = document.querySelector('#sidebar_wrapper');
> 		this.headerEl = document.querySelector('#header');
> 		this.sidebarToggleEl = document.querySelector('#sidebar_toggle');
> 
> 		if (this.sidebarEl && this.sidebarToggleEl) {
> 			this._handleSidebar();
> 			this._handleSidebarMenu();
> 		}
> 	},
> 	isSidebarCollapse() {
> 		return this._isSidebarCollapse();
> 	}
> }
> export default KTLayout;
> ```

Hi there, I did this but i got alot of hydratation errors

**Comment by laurisstepanovs** [comment]
Hi @tomichGIT,

I pushed the update for our `README.md`, in the latest Metronic version `./src/metronic/core/plugins/layouts/demo1` has the default export to setup integration example you just need to remove the html initialization code.

Also, fille `require('./src/metronic/core/plugins/layouts/demo1'),` is not needed anymore if you are using the source code from the latest Metronic version, the `tailwind.config.js` is already updated in https://github.com/keenthemes/metronic-tailwind-html-integration/commit/edc7341bf4884adab38f017deafe69a91eb0c91a.

We tested our latest integration example with the latest Metronic v9.0.3 source code and we were not able to reproduce this error. Could you please specify which Metronic version you are using?
