### ISSUE TITLE
Next js sidebar collapse not working

### ISSUE THREAD

**Issue by kyro95** [keenthemes/metronic-tailwind-html-integration#6]
Hi there, i managed to make next js setup running but sidebar collapse is totally broken

![Iscreenshot](https://i.imgur.com/Gpu2sTR.png)

**Comment by laurisstepanovs** [comment]
@kyro95 Are you using source code from the latest Metronic v9.0.3?

If you use the source code from the latest Metronic 9 version, ensure you have `@import "demos/demo1";` style import in your `metronic/css/styles.css`. If you are using the source code from Metronic older versions then you need to add `require('./src/metronic/core/plugins/layouts/demo1')` to `plugins` array in `tailwind.config.js`.

**Comment by kyro95** [comment]
> @kyro95 Are you using source code from the latest Metronic v9.0.3?
> 
> If you use the source code from the latest Metronic 9 version, ensure you have `@import "demos/demo1";` style import in your `metronic/css/styles.css`. If you are using the source code from Metronic older versions then you need to add `require('./src/metronic/core/plugins/layouts/demo1')` to `plugins` array in `tailwind.config.js`.

I'm actually using 9.0.1 and demo1 is imported in plugins

**Comment by laurisstepanovs** [comment]
@kyro95 
Do you see any errors in your browser console?

Could you try following the steps in the [README.md](https://github.com/keenthemes/metronic-tailwind-html-integration/tree/main/metronic-tailwind-next) and use the source code from Metronic v9.0.3?

**Comment by kyro95** [comment]
> @kyro95 Do you see any errors in your browser console?
> 
> Could you try following the steps in the [README.md](https://github.com/keenthemes/metronic-tailwind-html-integration/tree/main/metronic-tailwind-next) and use the source code from Metronic v9.0.3?

I did upgrade to Metronic 9.0.3, no errors in the console

**Comment by laurisstepanovs** [comment]
> > @kyro95 Do you see any errors in your browser console?
> > Could you try following the steps in the [README.md](https://github.com/keenthemes/metronic-tailwind-html-integration/tree/main/metronic-tailwind-next) and use the source code from Metronic v9.0.3?
> 
> I did upgrade to Metronic 9.0.3, no errors in the console

Unfortunately, we were not able to reproduce this problem with the latest Metronic version. Can you provide us with the source code of your app?
