### ISSUE TITLE
Media folder - Angular

### ISSUE THREAD

**Issue by ArsenioInojosa** [keenthemes/metronic-tailwind-html-integration#7]
There is a bug in the Angular documentation.

The correct path for the Media folder is src/assets/media and not src/assets/metronic/assets.

`Copy the media folder from the metronic-tailwind-html package's dist/assets/media directory into your Angular project's src/assets directory. The resulting directory structure should look like this: src/assets/metronic/assets .`

**Comment by faizalmy** [comment]
Thank you.

We have updated the Angular documentation to reflect the correct path for the Media folder.

The correct path is `src/assets/media`
