### ISSUE TITLE
Nextjs intergration didn't work

### ISSUE THREAD

**Issue by chetan1029** [keenthemes/metronic-tailwind-html-integration#8]
So I try to setup next js from metronic-tailwind-html-nextjs and from custom but its not working. It load the page without error but then it didn't not load any other page and give strange URL like http://localhost:3001/html/html/demo1/public-profile/projects/3-columns.html HELP 
<img width="1721" alt="Screenshot 2024-07-26 at 16 01 03" src="https://github.com/user-attachments/assets/028665ec-929e-473b-9061-1f5135f9c0ae">
<img width="1721" alt="Screenshot 2024-07-26 at 16 01 16" src="https://github.com/user-attachments/assets/a5f4b10d-8264-46c3-8a5c-c3a83ec09b79">

**Comment by laurisstepanovs** [comment]
Please note that apps in this repo are integration examples, apps include global style setup component initialization and layout markup. You can use this app as a starting point to add other pages and functions you can refer to our primary Metronic 9 HTML version and <a href="https://keenthemes.com/metronic/tailwind/docs/getting-started/installation">documentation</a>.
