### ISSUE TITLE
ReferenceError: KTDom is not defined on following metronic tailwind angular instructions.

### ISSUE THREAD

**Issue by Chcoflex** [keenthemes/metronic-tailwind-html-integration#9]
I was following the readme instructions for the Angular intergration with tailwind and recevied an error in the browser console which prevents further excution and loading of the app.

I am using metronic-tailwind-html v9.0.3

On The main branch of the metronic tailwind html intergration.

Followed instructions in readme with copying folders and renaming them from metronic-tailwind-angular to the current branch.

![image](https://github.com/user-attachments/assets/54c1cf34-1b21-46af-83a9-c65e086576f9)

**Comment by Chcoflex** [comment]
Update:
I followed the instructions from the url: https://keenthemes.com/metronic/tailwind/docs/getting-started/integration/angular
and not the **readme** file within the repo. This resolved that error.

**Comment by Chcoflex** [comment]
Now all the links result in "**Cannot GET /html/demo1/public-profile/profiles/default.html**".

I assume missing insturctions somewhere?

**Comment by faizalmy** [comment]
The sample project only shows the sample integration of the layout with one empty sample page. Check the Angular routers. To implement the other pages, you have to implement them.
